Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Importando paquetes

### Librer√≠a de manipulaci√≥n de datos 
import pandas as pd
pd.set_option('display.max_columns', 50)
pd.options.mode.chained_assignment = None  # default='warn'
pd.options.display.float_format = '{:,.2f}'.format

### Librer√≠a de √°lgebra
import numpy as np

### Librer√≠as para graficar
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib as mpl

### Customizamos para tener fondos transparentes con alta resoluci√≥n
mpl.rcParams['figure.dpi']= 300
mpl.rc("savefig", dpi=300)
plt.rcParams.update({
    "figure.facecolor":  (0.0, 0.0, 0.0, 0.0),
    "axes.facecolor":    (0.0, 0.0, 0.0, 0.0),
    "savefig.facecolor": (0.0, 0.0, 0.0, 0.0),
})
plt.rc('axes.spines', **{'bottom':True, 'left':True, 'right':False, 'top':False})

### Para formato local de fecha
import locale
locale.setlocale(locale.LC_TIME, '')

### Otros paquetes
import math
import os
import json as json
import datetime
import time
import IPython.display as display
from PIL import Image, ImageDraw, ImageFont
from IPython.display import display, HTML

### Solo de uso espor√°dico
import csv
from io import StringIO
import pkg_resources
import types

### Gracias a joelostblom (https://gitlab.com/joelostblom/session_info)
import session_info

### Pybtex
import pybtex.plugin
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-d384eb127edb>[0m in [0;36m<module>[0;34m[0m
[1;32m     46[0m [0;34m[0m[0m
[1;32m     47[0m [0;31m### Gracias a joelostblom (https://gitlab.com/joelostblom/session_info)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 48[0;31m [0;32mimport[0m [0msession_info[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     49[0m [0;34m[0m[0m
[1;32m     50[0m [0;31m### Pybtex[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'session_info'
ModuleNotFoundError: No module named 'session_info'

